### ISSUE TITLE
Compatibility with jetpack4.5

### ISSUE THREAD

**Issue by lghasemzadeh** [anion0278/mediapipe-jetson#1]
Hello,
Thank you for the tutorial.
Is this instruction works for jetpack 4.5 as well? if yes, where in the instruction I need to make changes?
I need jetpack 4.5 and mediapipe 0.8.9 or higher.
Thx

**Comment by anion0278** [comment]
Hello, I believe it should work without any problems since JetPack includes the same version of OpenCV and, most likely, the same version of Python. Unfortunately, currently I don't have the appropriate hardware to test if it installs successfully on JetPack 4.5. However, I recommend that you try installing it using the Python Wheel Installation instructions provided here: [Installation](https://github.com/anion0278/mediapipe-jetson#installation-for-clean-jetpack-46---461---python-wheel). It only takes a few minutes to try, and you will be able to verify if it's working right away using some simple script like this:
```
import cv2
import mediapipe as mp
import time

mpHands = mp.solutions.hands
hands = mpHands.Hands()
mpDraw = mp.solutions.drawing_utils

pTime = 0
cTime = 0

while True:
    img = cv2.imread("your_img.jpg")
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = hands.process(imgRGB)
    if results.multi_hand_landmarks:
        for handLms in results.multi_hand_landmarks:
            for id, lm in enumerate(handLms.landmark):
                h, w, c = img.shape
                cx, cy = int(lm.x*w), int(lm.y*h)
            mpDraw.draw_landmarks(img, handLms, mpHands.HAND_CONNECTIONS)

    cTime = time.time()
    fps = 1/(cTime-pTime)
    pTime = cTime

    cv2.putText(img, "FPS: " + str(int(fps)), (10, 70), cv2.FONT_HERSHEY_PLAIN, 3, (255, 0, 255), 3)

    cv2.imshow("Image", img)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()
```
If you encounter problems during installation, I may try to help you.

**Comment by anion0278** [comment]
@lghasemzadeh Did it work for you ?  :)
